services:
  # ----------------------------------------------------
  # 1. DATABASE SERVICE (MySQL)
  # ----------------------------------------------------
  db:
    image: mysql:8.0
    container_name: agency_mysql
    
    env_file:
      - .env
      
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS} 
      MYSQL_DATABASE: ${DB_NAME}

    volumes:
      - ./backend/dbproject.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

    ports:
      - "3307:3306"
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASS}"]
      interval: 5s
      timeout: 10s
      retries: 5
      
  # ----------------------------------------------------
  # 2. APPLICATION SERVICE (FastAPI)
  # ----------------------------------------------------
  api:
    build: 
      context: ./backend 
      dockerfile: Dockerfile # Looks for backend/Dockerfile
    container_name: agency_fastapi
    
    env_file:
      - .env

    environment:
      DB_HOST: db 
    
    depends_on:
      db:
        condition: service_healthy 

    ports:
      - "8000:8000"

# ----------------------------------------------------
# 3. Docker Volumes
# ----------------------------------------------------
volumes:
  db_data: